version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: polls
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "../wait-for-it.sh db:5432 -- python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    working_dir: /code/mysite
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
