version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: polls
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: >
      bash -c "dockerize -wait tcp://db:5432
      && pipenv install --system --dev
      && python3 manage.py migrate
      && python3 manage.py collectstatic --noinput
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
